flyhighblog/posts/forms.py
# Importing form validation and rendering library integrated in Flask
from flask_wtf import FlaskForm
# Importing form file input field
from flask_wtf.file import FileField, FileAllowed
# Importing required field types
from wtforms import (StringField, SubmitField, TextAreaField)
# Importing field validators
from wtforms.validators import (DataRequired)


# Defining form for creating new post
#   including form validation parameters
class PostForm(FlaskForm):
    title = StringField('Post Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    # For new post, uploading picture is required
    picture = FileField('Upload post picture',
                        validators=[DataRequired(),
                                    FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Post')


# Defining form for updating existing post
#   including form validation parameters
class UpdatePostForm(FlaskForm):
    title = StringField('Post Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    # When updating post, if picture is not changed, originally uploaded
    #   picture is kept
    picture = FileField('Change post picture',
                        validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Update')

flyhighblog/main/routes.py
# Importing required flask methods and functions
from flask import render_template, request, Blueprint
# Importing Flask pagination function
from flask_paginate import Pagination
# Importing Tools for working with MongoDB ObjectIds
from bson.objectid import ObjectId
# Importing variables from other application packages
from flyhighblog import mongo
from flyhighblog.main.utils import get_items


# Creating Blueprint object
main = Blueprint('main', __name__)


# Setting new variable to the context of templates - and can be used
#   in the base.html.
# users_all variable is used to generate list of authors for navbar
@main.context_processor
def context_processor():
    # Users data is pulled from database and sorted by their first name
    users = mongo.db.users.find().sort('first_name')
    # Converting MongoDB object to list of dictionaries
    users = [dict(user) for user in users]
    return dict(users_all=users)


# Index route - listing all posts
@main.route('/')
@main.route('/index')
def index():
    # Posts data is pulled from database and sorted by date in descending
    #   order
    posts = mongo.db.posts.find().sort('date_posted', -1)

    # Converting MongoDB object to list of dictionaries
    posts = [dict(post) for post in posts]

    # Amending list of dictionaries so as it contains required user
    #   specific data
    for post in posts:
        user = mongo.db.users.find_one({'_id': ObjectId(post['author'])})
        post['first_name'] = user['first_name'].title()
        post['last_name'] = user['last_name'].title()
        post['username'] = user['username']

    # Pagination parameters
    page = int(request.args.get('page', 1))
    per_page = 5
    offset = (page - 1) * per_page

    total = len(posts)

    pagination_posts = get_items(posts, offset=offset, per_page=per_page)

    # Pagination options - refer to https://pythonhosted.org/Flask-paginate/
    pagination = Pagination(page=page, per_page=per_page, total=total,
                            css_framework='bootstrap4', inner_window=1,
                            outer_window=0)

    # Rendering index.html template with list of all posts pulled from MongoDB
    # 'title' variable customizes web-page title
    return render_template('index.html',
                           posts=pagination_posts,
                           page=page,
                           per_page=per_page,
                           pagination=pagination,
                           title='Home')


# Retrieve file from database based on filename
@main.route('/file/<filename>')
def file(filename):
    return mongo.send_file(filename)

flyhighblog/posts/routes.py
# Importing functions for manipulating dates
from datetime import datetime
# Importing required flask methods and functions
from flask import (render_template, redirect, url_for, flash,
                   session, request, abort, Blueprint)
# Importing Tools for working with MongoDB ObjectIds
from bson.objectid import ObjectId
from bson.errors import InvalidId
# Importing variables from other application packages
from flyhighblog import mongo
from flyhighblog.posts.forms import PostForm, UpdatePostForm
from flyhighblog.posts.utils import (post_picture,
                                     post_picture_check_and_delete)


# Creating Blueprint object
posts = Blueprint('posts', __name__)


# Setting new variable to the context of templates - can be used
#   in the base.html
# users_all variable is used to generate list of authors for navbar
@posts.context_processor
def context_processor():
    # Users data is pulled from database and sorted by their first name
    users = mongo.db.users.find().sort('first_name')
    # Converting MongoDB object to list of dictionaries
    users = [dict(user) for user in users]
    return dict(users_all=users)


# Route for rendering New Post form; accessible only for
#   registered and logged users
@posts.route('/post/new', methods=['GET', 'POST'])
def new_post():
    # If user is logged in (i.e. 'user_id' is in session),
    #  allow access to new post
    if 'user_id' in session:

        # Defining form variable - PostForm
        form = PostForm()

        # Check if form inputs are valid
        if form.validate_on_submit():

            # Resize and save picture to database
            picture_fn = post_picture(form.picture.data)

            # Save information from the form to database
            post_doc = {
                    'title': form.title.data,
                    'date_posted': datetime.utcnow(),
                    'content': form.content.data,
                    'author': session['user_id'],
                    'picture': picture_fn,
                    }
            mongo.db.posts.insert_one(post_doc)

            # Flash message informing about successful creation of post
            flash('Your post has been created!', 'success')
            # Redirect to index.html
            return redirect(url_for('main.index'))

        # Render new_post.html
        return render_template('new_post.html', title='New Post', form=form)

    # If user is not logged in, redirect to login.html and save info about
    #   user's intention so as the corresponding page can be displayed after
    #   successful login.
    else:
        # Flash message informing user about the need to be logged in
        #   to be able to create a new post.
        flash('Please login to access this page.', 'info')
        # Redirect to log-in page
        return redirect(url_for('users.login', next=request.endpoint))


# Route for displaying post; accessible also for non-registered users
@posts.route('/post/<post_id>')
def post(post_id):
    # Check validity of ObjectId and return 404 if invalid
    try:
        ObjectId(post_id)
    except (InvalidId, TypeError):
        abort(404)
    post = mongo.db.posts.find_one_or_404({'_id': ObjectId(post_id)})

    # If post does not exist retutn 404
    if post is None:
        abort(404)

    # Converting MongoDB object to dictionary
    post = dict(post)
    user = mongo.db.users.find_one({'_id': ObjectId(post['author'])})

    # Amending post dictionary so as it contains required user
    #   specific data
    post['first_name'] = user['first_name'].title()
    post['last_name'] = user['last_name'].title()
    if 'profile_img' in user:
        post['profile_image'] = user['profile_img']
    else:
        post['profile_image'] = None

    # Rendering post.html
    return render_template('post.html', title=post['title'], post=post)


# Route for rendering Update Post form; accessible only for
#   registered and logged users
# Post can be updated only by its author
@posts.route('/post/<post_id>/update',  methods=['GET', 'POST'])
def update_post(post_id):
    # If user is logged in (i.e. 'user_id' is in session),
    #  allow access to update post
    if 'user_id' in session:

        # Check validity of ObjectId and return 404 if invalid
        try:
            ObjectId(post_id)
        except (InvalidId, TypeError):
            abort(404)

        posts = mongo.db.posts
        post = mongo.db.posts.find_one_or_404({'_id': ObjectId(post_id)})

        # If post does not exist retutn 404
        if post is None:
            abort(404)

        # If logged user is not author of post, return 403
        if post['author'] != session['user_id']:
            abort(403)

        # Defining form variable - UpdatePostForm
        form = UpdatePostForm()

        # Check if form inputs are valid
        if form.validate_on_submit():

            # Checking if there are picture data in the form
            if form.picture.data:

                # Checking if user already inserted post picture in the past.
                # If yes, delete the old file from the database
                post_picture_check_and_delete(post)

                # Resize and save picture to database
                picture_fn = post_picture(form.picture.data)

                # Save file name reference to post document
                posts.update({'_id': ObjectId(post_id)},
                             {'$set': {
                                        'picture': picture_fn,
                                      }
                              })

            # Update only those post details that have been changed
            # All other details shall remain same
            posts.update({'_id': ObjectId(post_id)},
                         {'$set': {
                                    'title': form.title.data,
                                    'content': form.content.data,
                                  }
                          })

            # Generate flash message on successful post update
            flash('Post has been updated!', 'success')

            # Redirect to updated post
            return redirect(url_for('posts.post', post_id=post_id))

        # Pull data from database and insert them to post update form
        elif request.method == 'GET':
            form.title.data = post['title']
            form.content.data = post['content']
        return render_template('update_post.html', title='Update Post',
                               form=form, post_id=post_id)

    # If user is not logged in, redirect to login.html and save info about
    #   user's intention so as the corresponding page can be displayed after
    #   successful login.
    else:
        # Flash message informing user about the need to be logged
        #   in to be able to update existing post.
        flash('Please login to access this page.', 'info')
        # Redirect to login page
        return redirect(url_for('users.login', next=request.endpoint))


# Route for deleting post; accessible only for
#   registered and logged users
# Post can be deleted only by its author
@posts.route("/post/<post_id>/delete", methods=['POST'])
def delete_post(post_id):
    # If user is logged in (i.e. 'user_id' is in session),
    #  allow post delete
    if 'user_id' in session:

        # Check validity of ObjectId and return 404 if invalid
        try:
            ObjectId(post_id)
        except (InvalidId, TypeError):
            abort(404)
        post = mongo.db.posts.find_one_or_404({'_id': ObjectId(post_id)})

        # If post does not exist retutn 404
        if post is None:
            abort(404)

        # If logged user is not author of post, return 403
        if post['author'] != session['user_id']:
            abort(403)

        # Checking if user already inserted post picture in the past.
        # If yes, delete the old file from the database
        post_picture_check_and_delete(post)

        # Delete post from database
        mongo.db.posts.delete_one({'_id': ObjectId(post_id)})

        # Flash message informing user that the post was deleted
        flash('Post has been deleted.', 'success')

        # Redirect to index.html
        return redirect(url_for('main.index'))
    # If user is not logged in, redirect to login.html and save info about
    #   user's intention so as the corresponding page can be displayed after
    #   successful login.
    else:
        # Flash message informing user about the need to be logged in
        #   to be able to delete post.
        flash('Please login to access this page.', 'info')
        # Redirect to login page
        return redirect(url_for('users.login', next=request.endpoint))

flyhighblog/templates/account.html
{% extends "base.html" %}
<!-- Defining variable for highlighting active links in navbar -->
{% set active_page = "account" %}
{% block content %}
<div class="account-container">
	<div class="media-body">
		<div class="row">
            <div class="col account-image">
                <!-- If user changed profile image, diplay changed image. Otherwise, display static default profile image. -->
                {% if user['profile_img'] %}
                    <img class="rounded-circle account-img" src="{{ url_for('main.file', filename=user['profile_img']) }}" alt="Profile Image">
                {% else %}
                    <img class="rounded-circle account-img" src="{{ url_for('static', filename='img/profile-image/userimage.jpg') }}" alt="Profile Image">
                {% endif %}
            </div>        
            <div class="col col-12 col-sm-7">
                <div class="media-body account-title">
                    <!-- User first name and last name -->
                    <h2 class="account-heading">{{ user['first_name'].title() }} {{ user['last_name'].title() }}</h2>
                    <!-- User email -->
                    <p>{{ user['email'] }}</p>
                    <br>
                    <br>
                </div>
            </div>
        </div>
	</div>
	<!-- UPDATE ACCOUNT DETAILS FORM -->
	<div>
		<!-- novalidate enctype="multipart/form-data" is required for forms with file upload control -->
        <form method="POST" action="" novalidate enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Account Info</legend>
				<div class="form-group">
					<!-- First name input - label -->
					{{ form.firstname.label(class="form-control-label") }}
					<!-- Checking if information passed by user is valid -->
					{% if form.firstname.errors %}
					<!-- If information is invalid, provide user with corresponding feedback -->
					{{ form.firstname(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.firstname.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					<!-- If information is valid, allow user to submit information -->
					{{ form.firstname(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group">
					<!-- Last name input - label -->
					{{ form.lastname.label(class="form-control-label") }}
					<!-- Checking if information passed by user is valid -->
					{% if form.lastname.errors %}
					<!-- If information is invalid, provide user with corresponding feedback -->
					{{ form.lastname(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.lastname.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					<!-- If information is valid, allow user to submit information -->
					{{ form.lastname(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					<!-- Username input - label -->
					{{ form.username.label(class="form-control-label") }}
					<!-- Checking if information passed by user is valid -->
					{% if form.username.errors %}
					<!-- If information is invalid, provide user with corresponding feedback -->
					{{ form.username(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					<!-- If information is valid, allow user to submit information -->
					{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					<!-- Email input - label -->
					{{ form.email.label(class="form-control-label") }}
					<!-- Checking if information passed by user is valid -->
					{% if form.email.errors %}
					<!-- If information is invalid, provide user with corresponding feedback -->
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					<!-- If information is valid, allow user to submit information -->
					{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
                <div class="form-group">
					<!-- Picture input - label -->
					{{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    <!-- If information is invalid, provide user with corresponding feedback -->
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
						<span class="text-danger">{{ error }}</span><br>
						{% endfor %}
                    {% endif %}
                </div>
			</fieldset>
			<!-- Sign up button -->
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-secondary") }}
                <a class="btn btn-outline-danger" href="{{ url_for('main.index') }}">Cancel</a>
			</div>
		</form>
	</div>
</div>
{% endblock content %}

flyhighblog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

	<!-- Bootstrap CSS -->
	<link type="text/css" rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />

	<!-- Fontawesome -->
	<link type="text/css" rel="stylesheet"
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.css" />

	<!-- Custom CSS -->
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/base-style.css') }}" />
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/index-style.css') }}" />
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/account-style.css') }}" />
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/post-style.css') }}" />

    <!-- Dynamic page title -->
	{% if title %}
	<title>FlyHigh Blog - {{ title }}</title>
	{% else %}
	<title>FlyHigh Blog</title>
	{% endif %}

	<!-- Favicon -->
	<link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon" />
</head>

<body>
    <!-- Header with Navbar -->
	<header class="site-header">
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
			<div class="container">
				<a class="navbar-brand"
					href="{{ url_for('main.index') }}"><span class="logo"><i class="fas fa-paper-plane"></i></span>
					FlyHigh</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			                <span class="navbar-toggler-icon"></span>
			            </button>

				<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
					<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
						<li class="nav-item">
							<a class="nav-link {{ 'active' if active_page == 'home' else 'hvr-underline-from-left' }}"
								href="{{ url_for('main.index') }}">Home</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle {{ 'active' if active_page == 'user_posts' else 'hvr-underline-from-left' }}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
								aria-haspopup="true" aria-expanded="false">
								Authors
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<!-- Generating dropdown list based on registered user stored in database -->
                                {% for user in users_all %}
                                    <a class="dropdown-item" href="{{ url_for('users.user_posts', username=user.username) }}">{{ user.first_name }} {{ user.last_name }}</a>
                                {% endfor %}
							</div>
						</li>
					</ul>
					<ul class="navbar-nav mt-2 mt-lg-0">
						<!-- Displaying links corresponding to user status (authenticated/logged out), active class is assigned based on displayed template -->
                        {% if 'user_id' in session %}
                            <li class="nav-item">
                                <a class="nav-link {{ 'active' if active_page == 'new_post' else 'hvr-underline-from-left' }}" href="{{ url_for('posts.new_post') }}">New Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ 'active' if active_page == 'account' else 'hvr-underline-from-left' }}" href="{{ url_for('users.account') }}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link hvr-underline-from-left" href="{{ url_for('users.logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {{ 'active' if active_page == 'login' else 'hvr-underline-from-left' }}" href="{{ url_for('users.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ 'active' if active_page == 'register' else 'hvr-underline-from-left' }}" href="{{ url_for('users.register') }}">Register</a>
                            </li>
                        {% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</header>

    <!-- Hero Image -->
	<div id="hero-image" class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4">Aviation Blog</h1>
            <hr>
			<p class="lead">The latest news and opinions.</p>
		</div>
	</div>

    <!-- Main Content -->
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Displaying flash messages to provide user with guidance -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                       {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                       {% endfor %} 
                    
                    {% endif %}
                {% endwith %}
                <!-- Area where the templates are rendered -->
                {% block content %}{% endblock %}
			</div>
		</div>
	</div>

  <!-- --------FOOTER------------ -->
  <footer>
    <div class="footer-area">
      <div class="container">
        <div class="row">
          <!-- The first footer column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <div class="footer-logo">
                  <h2><span><i class="fas fa-paper-plane"></i></span> FlyHigh</h2>
                </div>

                <p>Aviation blog for enthusiasts and professionals.</p> 
                <p>The latest news and opinions.</p>
                <div class="footer-icons">
                  <ul>
                    <li>
                      <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                      <a href="https://twitter.com/" target="_blank"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                      <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                      <a href="https://www.pinterest.com/" target="_blank"><i class="fab fa-pinterest-p"></i></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- The second footer column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <h4>Contact</h4>
                <p>FlyHigh.com<br>
                Navigational 787<br>
                155 00  Prague 5<br>
                Czech Republic</p>
                <p>Email: info@flyhigh.com</p>
                
              </div>
            </div>
          </div>
          <!-- The third footer column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="footer-content">
              <div class="footer-head">
                <h4>Flicker</h4>
                <div class="flicker-img">
                  <a href="https://www.flickr.com/" target="_blank"><img src="{{ url_for('static', filename='img/flicker/1.jpg') }}" alt="Flicker image thumbnail"></a>
                  <a href="https://www.flickr.com/" target="_blank"><img src="{{ url_for('static', filename='img/flicker/2.jpg') }}" alt="Flicker image thumbnail"></a>
                  <a href="https://www.flickr.com/" target="_blank"><img src="{{ url_for('static', filename='img/flicker/3.jpg') }}" alt="Flicker image thumbnail"></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <span><i class="fas fa-paper-plane"></i></span> FlyHigh. All Rights Reserved
              </p>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </footer>

	<!-- Bootstrap JavaScript -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
	<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js">
	</script>
    
</body>

</html>

flyhighblog/templates/post.html
{% extends "base.html" %}
<!-- Defining variable for highlighting active links in navbar -->
{% set active_page = "single_post" %}
{% block content %}
<!-- Loop through the posts and generate list of posts -->
<div class="media post-single">
	<div class="media-body">
		<div class="row">
			<div class="col-12">
				<div class="wrapper picture-wrapper">
					<!-- If respective post picture is found in database, picture is displayed. Otherwise, default static picture is displayed. -->
                    {% if post['picture'] %}
					<img class="rounded" src="{{ url_for('main.file', filename=post['picture']) }}" alt="Post Image">
                    {% else %}
					<img class="rounded" src="{{url_for('static', filename='img/post-image/sample-image.jpg')}}" alt="Post Image">
                    {% endif %}
                </div>
			</div>
		</div>
		<div class="row post-content">
			<div class="col profile-image-column">
				<!-- If user changed profile image, diplay changed image. Otherwise, display static default profile image. -->
                {% if post['profile_image'] %}
		    		<img class="rounded-circle post-account-img" src="{{ url_for('main.file', filename=post['profile_image']) }}" alt="Profile Image">
                {% else %}
					<img class="rounded-circle post-account-img" src="{{ url_for('static', filename='img/profile-image/userimage.jpg') }}" alt="Profile Image">
                {% endif %}
            </div>
			<div class="col">
				<div class="row row-meta">
					<div class="col-12">
						<p><a class="author-link" href="#"><i class="fas fa-feather-alt"></i>
								<!-- First name and last name -->
                                {{ post.first_name }} {{ post.last_name }}
							</a></p>
					</div>
				</div>
				<div class="row row-meta">
					<div class="col-12">
						<p class="text-muted"><i class="far fa-calendar"></i>
							<!-- Date the post was created -->
                            {{ post.date_posted.strftime('%d %B %Y') }}</p>
					</div>
				</div>
			</div>
		</div>
		<!-- If logged user is author of the post, display UPDATE and DELETE buttons -->
        <!-- Delete action needs to be reconfirmed - modal message is displayed -->
        {% if post.author == session['user_id'] %}
			<div class="row">
				<div class="col-6 change-buttons">
					<a class="btn btn-outline-secondary btn-sm"
						href="{{ url_for('posts.update_post',  post_id=post._id) }}">Update</a>
				</div>
				<div class="col-6 change-buttons">
					<button type="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete</button>
				</div>
			</div>
		{% endif %}
		<div class="row">
			<div class="col-12">
				<hr>
			</div>
		</div>

		<div class="row post-text">
			<div class="col-12">
				<!-- Post title -->
                <h5>{{ post.title.title() }}</h5>
			</div>
			<div class="col-12">
				<!-- Post content -->
                <p>{{ post.content }}</p>
			</div>
		</div>

	</div>
</div>

<!-- Bootstrap Modal for deletion confirmation -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.delete_post', post_id=post._id) }}" method="POST">
					<input class="btn btn-outline-danger" type="submit" value="Delete">
                </form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}